<?php
	$methodsAllowed = array(
		"generateToken" => "POST",
		"refreshToken" => "POST",
		"revokeToken" => "POST",
		"reqTicketLatest" => "GET",
		"reqTicketLatest" => "GET",
		"reqTicketStatus" => "GET",
		"createTicket" => "POST",
		"createLead" => "POST",
		"addPerson" => "POST",
		"updatePerson" => "POST",
		"searchPerson" => "GET",
		"searchPersonNew" => "GET",
		"fnEscalationExecuterule" => "POST"
	);
	$allowedDomain = array("c-zentrix.com","localhost","127.0.0.1");
	$allowedDomainTpt = array("c-zentrix.com");
	$dataAllowedTpt = 60; 
	$token_expiry_period = (1*24*60*60);
	define ("_TOKEN_EXPIRY_PERIOD_",$token_expiry_period);
	$functionConfiguration=array(
		"recentTicket"=>array("domainCheck","sessionCheck"),
		//"getTicketCreationTime"=>array("domainCheck"),
		//"reqTicketLatest"=>array("domainCheck","sessionCheck"),   //will b called only by tpt
		//"fnEscalationExecuterule"=>array("domainCheck"),
		//"reqTicketStatus"=>array("domainCheck","sessionCheck"),    //will b called only by tpt
		"get_mandatory_flds"=>array("domainCheck","sessionChecck"),
		"getCustID"=>array("domainCheck","sessionCheck"),
		"generateDocket"=>array("domainCheck","sessionCheck"),
		"omniLogout"=>array("domainCheck"),
		"omniLogin"=>array("domainCheck"),
		"omniSignup"=>array("domainCheck"),
		"mapCallTicket"=>array("domainCheck"),
		//"createTicket"=>array("domainCheck","sessionCheck"),
		"checkPerson"=>array("domainCheck"),
		"addPerson"=>array("domainCheck"),
		"updatePerson"=>array("domainCheck"),
		//"searchPersonNew"=>array("domainCheck"),
		"searchPerson"=>array("domainCheck","sessionCheck"),
		"resetPassword"=>array("domainCheck"),
		"resetPasswordLink"=>array("domainCheck","sessionCheck"),
		"updateTickets"=>array("domainCheck","sessionCheck"),
		"updateTicketMobile"=>array("domainCheck","sessionCheck"),
		"assignTicketMobile"=>array("domainCheck","sessionCheck"),
		"privateNotetMobile"=>array("domainCheck","sessionCheck"),
		"myTickets"=>array("domainCheck","sessiionCheck"),
		"searchTicket"=>array("domainCheck","sessionCheck"),
		"applyChange"=>array("domainCheck","sessionCheck"),
		"addUser"=>array("domainCheck"),
		"addUuidUser"=>array("domainCheck"),
		"ackAddUserProvision"=>array("domainCheck"),
		"expireUserProvision"=>array("domainCheck"),
		"updateUser"=>array("domainCheck"),
		"addDepartment"=>array("domainCheck"),
		"updateDepartment"=>array("domainCheck"),
		"addProvision"=>array("domainCheck"),
		"createLead"=>array("domainCheck","sessionCheck"),
		"searchLead"=>array("domainCheck","sessionCheck"),
		"recentLead"=>array("domainCheck","sessionCheck"),
		"callConnect"=>array("domainCheck"),
		"callDisconnect"=>array("domainCheck"),
		"getMaildata"=>array("domainCheck","sessionCheck"),
		"getMailThreaddata"=>array("domainCheck","sessionCheck"),
		"getMailThreadattachment"=>array("domainCheck","sessionCheck"),
		"followupDetails"=>array("domainCheck","sessionCheck"),
		"deletePerson"=>array("domainCheck"),
		"deleteDepartment"=>array("domainCheck"),
		"deleteUser"=>array("domainCheck"),
	);
?>